#!/bin/sh
set -e

DST_DIR=$(php --ini | grep "Scan for additional .ini files in:" | awk '{print $7}')
EXT_NAME=xdebug
EXT_DIR=$(php -i | grep -E ^extension_dir | awk '{print $5}')
# EXT_TYPE can be either "extension" or "zend_extension"
EXT_TYPE=zend_extension

if [ $1 = "on" ]; then
	echo "${EXT_TYPE}=${EXT_DIR}/${EXT_NAME}.so" > ${DST_DIR}/${EXT_NAME}.ini
	echo "${EXT_NAME} ${EXT_TYPE} activated"
else
	rm -f ${DST_DIR}/${EXT_NAME}.ini
	echo "${EXT_NAME} ${EXT_TYPE} deactivated"
fi
